[package]
name = "stun-server-list"
description = "Fetches a list of public STUN servers and outputs them formatted as a rust source file"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tokio   = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
reqwest = { workspace = true, features = ["rustls-tls"] }
